### ISSUE TITLE
dataset preparation

### ISSUE THREAD

**Issue by SreenijaK** [Alpha-Monocerotis/PDF_FigureTable_Extraction#1]
what is the size of your dataset and how did you annotate the dataset

**Comment by dreamyang-liu** [comment]
> what is the size of your dataset and how did you annotate the dataset

1. The dataset contains about 1100 images.
2. Labelimg, but I transformed the annotation from Yolo3 dataset format, code for transformation is not included in this repo

**Comment by SreenijaK** [comment]
can you share the code for transformations.?

**Comment by dreamyang-liu** [comment]
> can you share the code for transformations.?

Sorry, the code was removed long ago. But transformation is not necessary, you can use labelme to annotate dataset without transformation.
